name: go-tests
on:
  workflow_call:
    inputs:
      go-version-file:
        type: string
        required: false
        default: go.mod
      packages:
        type: string
        required: false
        default: ./...
      race:
        type: boolean
        required: false
        default: false
      coverprofile:
        type: string
        required: false
        default: coverage.out
      upload-coverage:
        type: boolean
        required: false
        default: true

jobs:
  tests:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up test git config
        run: |
          git config --global user.email "test@example.com"
          git config --global user.name "Test User"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ${{ inputs.go-version-file }}
          cache: true

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-

      - name: Download deps
        run: go mod download

      - name: Run tests
        run: |
          if [ "${{ inputs.race }}" = "true" ]; then
            go test -race -coverprofile="${{ inputs.coverprofile }}" -covermode=atomic ${{ inputs.packages }}
          else
            go test -coverprofile="${{ inputs.coverprofile }}" -covermode=atomic ${{ inputs.packages }}
          fi

      - name: Upload coverage artifact
        if: ${{ inputs.upload-coverage }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ${{ inputs.coverprofile }}